# Generated by Django 3.2.5 on 2022-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaDeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('PENDING', 'pending'), ('IN TRANSIT', 'in transit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=30)),
                ('pizza_size', models.CharField(choices=[('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large'), ('EXTRA LARGE', 'extra large')], default='SMALL', max_length=30)),
                ('quantity', models.IntegerField()),
                ('flavour', models.CharField(max_length=30)),
                ('customer_location', models.CharField(max_length=30)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
